Repository hackslash-nitp/cura, pull requests merged in 2022-10, with the labels that each got.

#33 Add intro screen
  assets/Group 44.png
  lib/individual/info_page.dart
  lib/startup_screens/intro_screen.dart
  lib/startup_screens/login.dart
  lib/startup_screens/splash_screen1_3.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#39 35 want to add readmemd file
  README.md
  android/build.gradle
  assets/health1.png
  assets/screenshot/WhatsApp Image 2022-10-05 at 6.20.52 PM (1).jpeg
  assets/screenshot/WhatsApp Image 2022-10-05 at 6.20.52 PM.jpeg
  assets/screenshot/WhatsApp Image 2022-10-05 at 6.20.53 PM (1).jpeg
  assets/screenshot/WhatsApp Image 2022-10-05 at 6.20.53 PM (2).jpeg
  assets/screenshot/WhatsApp Image 2022-10-05 at 6.20.53 PM.jpeg
  assets/screenshot/WhatsApp Image 2022-10-05 at 6.20.54 PM.jpeg
  lib/individual/health.dart
  lib/main.dart
  pubspec.yaml
Labels: hacktoberfest, hacktoberfest-accepted

#40 35 want to add readmemd file
  README.md
  android/build.gradle
  assets/health1.png
  assets/screenshot/WhatsApp Image 2022-10-05 at 6.20.52 PM (1).jpeg
  assets/screenshot/WhatsApp Image 2022-10-05 at 6.20.52 PM.jpeg
  assets/screenshot/WhatsApp Image 2022-10-05 at 6.20.53 PM (1).jpeg
  assets/screenshot/WhatsApp Image 2022-10-05 at 6.20.53 PM (2).jpeg
  assets/screenshot/WhatsApp Image 2022-10-05 at 6.20.53 PM.jpeg
  assets/screenshot/WhatsApp Image 2022-10-05 at 6.20.54 PM.jpeg
  lib/individual/health.dart
  lib/main.dart
  pubspec.yaml
Labels: hacktoberfest, hacktoberfest-accepted

#41 Update readme.md file
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#44 Issue #43 , auto focus of keyboard on login page, solved
  lib/individual/health.dart
  lib/startup_screens/login.dart
Labels: bug, hacktoberfest, hacktoberfest-accepted

#46 Solved #45 , Changed dimensions of individual homepage
  lib/individual/health.dart
  lib/individual/home_page_individual.dart
  lib/main.dart
  pubspec.lock
Labels: bug, hacktoberfest, hacktoberfest-accepted

#48 #47 Solved , Spend Time UI fixed
  lib/individual/spend_time.dart
  lib/individual/support_team_page.dart
  lib/main.dart
Labels: bug, hacktoberfest, hacktoberfest-accepted

#50 Solved #49, Bottom Navigation Bar Bug fixed.
  lib/individual/info_page.dart
  lib/individual/user_chats_menu.dart
  lib/organization/postfeed.dart
  lib/shared/widgets/navigation-bar.dart
Labels: bug, hacktoberfest, hacktoberfest-accepted

#56 Fixed Named Routing
  lib/individual/account_setup.dart
  lib/individual/adopt.dart
  lib/individual/donation_page.dart
  lib/individual/health.dart
  lib/individual/home_page_individual.dart
  lib/individual/info_page.dart
  lib/individual/spend_time.dart
  lib/individual/user_chat_screen.dart
  lib/individual/user_chats_menu.dart
  lib/main.dart
  lib/organization/account_setup.dart
  lib/organization/org_chat_screen.dart
  lib/organization/org_chats_menu.dart
  lib/organization/postfeed.dart
  lib/shared/navigation.dart
  lib/shared/services/RouteGenerator.dart
  lib/shared/services/firebase_authentication.dart
  lib/shared/services/stringScreenArguments.dart
  lib/shared/widgets/navigation-bar.dart
  lib/startup_screens/create_account.dart
  lib/startup_screens/intro_screen.dart
  lib/startup_screens/login.dart
  lib/startup_screens/preview_page.dart
  lib/startup_screens/splash_screen1_3.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#61 Fixed Overflow on Login Page
  lib/startup_screens/login.dart
Labels: bug, hacktoberfest, hacktoberfest-accepted

#62 Routining and UI modification done #59
  lib/organization/Widgets/mydrawer.dart
  lib/startup_screens/splash_slide.dart
Labels: hacktoberfest, hacktoberfest-accepted

#69 Solved #64 : Backend on Individual_Info page done
  lib/individual/info_page.dart
  lib/main.dart
  lib/shared/services/firebase_database.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#71 Improved UI with responsive icons
  lib/organization/postfeed.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#77 Use UID to display appropriate user_data
  lib/individual/info_page.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#70 used ScreenUntilinit to implement new UI
  lib/individual/info_page.dart
  lib/organization/postfeed.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#85 Solves #84 : Photo added in spend time page
  assets/spendTime.png
  lib/individual/spend_time.dart
  lib/main.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, urgent
